language: scala
sudo: required
jdk: oraclejdk8
script:
- ./src/test/resources/setup_travis.sh
- sbt scalafmt::test test:scalafmt::test sbt:scalafmt::test +test:compile "+ test"
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
